name = "GH19"
uuid = "91947a82-a5b4-404a-862e-a85adaeb659d"
authors = ["G Jake Gebbie <ggebbie@whoi.edu>"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
